### ISSUE TITLE
Experimental personal access tokens not accepted in CLI

### ISSUE THREAD

**Issue by jnorris441** [supabase/cli#1033]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The CLI does not accept access tokens generated at https://app.supabase.com/account/tokens

## To Reproduce

1. create an access token in https://app.supabase.com/account/tokens
2. pass into the CLI the environment variable SUPABASE_ACCESS_TOKEN
3. Error reads "Invalid access token format. Must be like `sbp_0102...1920`."

## Expected behavior

Should accept the token from the token admin. The tokens start with "sbp_v0_" instead of "sbp_0102".

## System information

- OS: macOS
- Version of supabase: 1.50.12
- Version of Node.js: v20.0.0

**Comment by sweatybridge** [comment]
Hi @jnorris441, there are 2 types of token that can be generated, classic and experimental. The CLI only accepts classic token which can be created by clicking "Generate new token" directly instead of expanding the dropdown.

<img width="474" alt="Screenshot 2023-04-25 at 11 25 52 AM" src="https://user-images.githubusercontent.com/1639722/234167426-97847c79-0fa1-4e0d-b1f9-4991c88585fb.png">

**Comment by jnorris441** [comment]
@sweatybridge thank you, that is not obvious from the docs or the explanation on the access token page.
