### ISSUE TITLE
Supabase db remote commit failing

### ISSUE THREAD

**Issue by oliviercperrier** [supabase/cli#121]
# Bug report

## Describe the bug

When running supabase db remote commit the following error occur: `Error: unexpected end of JSON input`

## To Reproduce

1. Run: `supabase init`
2. Run: `supabase db remote set [your-db-url]`
3. Run: `supabase db remote commit`

## Expected behavior

Should work as excepted and as said in the documentation: https://github.com/supabase/cli/tree/main/examples/tour

## System information

- OS: macOS
- Version of supabase cli: 0.15.10

**Comment by soedirgo** [comment]
Could be the same issue as https://github.com/supabase/cli/issues/116 - I've updated the CLI to validate the URL passed to `db remote set` in v0.15.12.

**Comment by damianfrizzi** [comment]
I have the same problem using `0.15.15`. What I have tried

- I have created a new Supabase project and used a password that does not contain any characters that require url encoding. Setting the remote db is possible but it fails when executing the commit command.
- I built the newest version from source and ran it agains my project. For me it fails [here](https://github.com/supabase/cli/blob/3a3f20bfa808bd13f8ff89c6e0c434ec3b6b1847/internal/utils/utils.go#L421). Maybe it's related to https://github.com/supabase/pgadmin4/issues/24?
- Since the old `link` command worked for me at some point, I tried to downgrade the cli to `0.12.4`. I checked out `68e580d` and ran the old `link` command by building from source (I also had to cherry-pick [this](https://github.com/supabase/cli/pull/91)). I got the message ```Finished `supabase link`.``` although no `XX_link.sql` migration was created.

I have no experience with Go, so I don't know if this information is helpful.

**Comment by jamesyu** [comment]
I am also getting this, on a relatively simple db that I just set up.

I don't believe there's anything in the password that requires url escaping.

Any word on this issue?

**Comment by soedirgo** [comment]
I haven't been able to replicate this, but I think it might be what Damian linked above (some logging in the schema diff). I'm currently working on other open issues, but will loop back once I have any updates.

**Comment by damianfrizzi** [comment]
I just tried the latest cli version `0.17.0` with a fresh supabase project and it worked. 

I created a dump of the old database structure and applied it to the new one via a migration. On the old, "broken" project there were some tables that had "supabase-admin" as an owner. I had to change this to "postgres". Not sure this is related to this issue, though.

**Comment by soedirgo** [comment]
Closing this for staleness - there's been a lot of change since this issue was raised, so if anyone's still bumping into this, please create a new issue.
