### ISSUE TITLE
service not healthy: realtime-dev.supabase_realtime

### ISSUE THREAD

**Issue by venvadlamani** [supabase/cli#1296]
**Describe the bug**
not able to start second project on my macbook with intel chip (works fine on macbook with arm chip)

**To Reproduce**
try to deploy second project to Docker on macbook with intel chip

**Expected behavior**
should be able to deploy multiple supabase projects to local docker. 

**Screenshots**
```
23:28:41.207 [debug] QUERY OK db=5.9ms
INSERT INTO "tenants" ("external_id","jwt_secret","max_bytes_per_second","max_channels_per_client","max_concurrent_users","max_events_per_second","max_joins_per_second","name","inserted_at","updated_at","id") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ["realtime-dev", "iNjicxc4+llvc9wovDvqymwfnj9teWMlyOIbJ8Fh6j2WNU8CIJ2ZgjR6MUIKqSmeDmvpsKLsZ9jgXJmQPpwL8w==", 100000, 100, 200, 100, 500, "realtime-dev", ~N[2023-07-08 23:28:41], ~N[2023-07-08 23:28:41], <<91, 153, 187, 10, 233, 87, 77, 185, 170, 85, 241, 157, 225, 126, 152, 76>>]
23:28:41.241 [debug] QUERY OK db=28.2ms
INSERT INTO "extensions" ("settings","tenant_external_id","type","inserted_at","updated_at","id") VALUES ($1,$2,$3,$4,$5,$6) [%{"db_host" => "sXy/++n+kxlWBT3iaMB+JCbKZ00yo3bzBr0E04l4zQU=", "db_name" => "sWBpZNdjggEPTQVlI52Zfw==", "db_password" => "sWBpZNdjggEPTQVlI52Zfw==", "db_port" => "+enMDFi1J/3IrrquHHwUmA==", "db_user" => "uxbEq/zz8DXVD53TOI1zmw==", "ip_version" => 4, "poll_interval_ms" => 100, "poll_max_changes" => 100, "poll_max_record_bytes" => 1048576, "publication" => "supabase_realtime", "region" => "us-east-1", "slot_name" => "supabase_realtime_replication_slot"}, "realtime-dev", "postgres_cdc_rls", ~N[2023-07-08 23:28:41], ~N[2023-07-08 23:28:41], <<212, 207, 117, 150, 146, 145, 66, 151, 152, 175, 175, 251, 76, 184, 197, 87>>]
23:28:41.245 [debug] QUERY OK db=3.8ms
commit []
supabase_pg_meta_projectjuniper container logs:

> @supabase/postgres-meta@0.0.0-automated start
> node dist/server/server.js

(node:47) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{"level":"info","time":"2023-07-08T23:28:39.475Z","pid":47,"hostname":"e0981e53e6df","msg":"Server listening at http://0.0.0.0:8080"}
{"level":"info","time":"2023-07-08T23:28:39.502Z","pid":47,"hostname":"e0981e53e6df","msg":"Server listening at http://0.0.0.0:8081"}
service not healthy: [realtime-dev.supabase_realtime_projectjuniper supabase_pg_meta_projectjuniper]

```

**Desktop (please complete the following information):**
 - OS: macbook air - sonoma 14
```
 supabase --version
1.75.3
```
```
docker --version
Docker version 24.0.2, build cb74dfc

```
```
 node --version
v18.16.1

```

**Comment by venvadlamani** [comment]
now i am not even able to start a single project. same error

**Comment by xHergz** [comment]
@venvadlamani any luck with this? I have the [same issue](https://github.com/supabase/cli/issues/778#issuecomment-1645816323) but with `supabase_studio`.

**Comment by Rykuno** [comment]
same issue.

**Comment by toddsampson** [comment]
I had the same issue and was about to get it working by updating Studio. I saw in another post related to running Supabase self-hosted (not local development) that there is an issue with supabase/studio:0.23.06. As such, if you fork this project and change line 23 in `internal/utils/misc.go` from `StudioImage = "supabase/studio:v0.23.06"` to `StudioImage = "supabase/studio`, run `go build -o supabase .` to build the binary file and then copy it over the existing `node_modules/supabase/bin/supabase` in your project and you should be good to go. Be sure to run `npx supabase stop --no-backup` before you run `npx supabase start` again.

I didn't want to put in a PR for this since I just removed the version number and couldn't figure out the correct version to use that matched the latest Docker build. That said, feel free to grab the updated binary or source from my fork to build it yourself: https://github.com/toddsampson/cli

**Comment by sweatybridge** [comment]
Could you try the fix here for intel macs? https://github.com/supabase/cli/issues/1083#issuecomment-1691431279

**Comment by dw820** [comment]
Same issue happened to me, and I tried running `supabase start --debug` then it worked.

**Comment by sweatybridge** [comment]
We've released some realtime improvements recently. Feel free to reopen if this is still an issue.
