### ISSUE TITLE
Include JWT secret in output of "supabase projects api-keys"

### ISSUE THREAD

**Issue by cdimitroulas** [supabase/cli#1317]
**Is your feature request related to a problem? Please describe.**
We use the JWT secret in our app and it would be great to have a way to dynamically get this value for a newly created supabase project without using the UI. 
In particular, this would move us closer to being able to deploy PR previews as we then have a way to:
- Dynamically create a Supabase project with `supabase projects create`
- Dynamically get API keys + secrets with `supabase projects api-keys` (assuming this feature request is accepted)
- Dynamically delete a Supabase project with `supabase projects delete` once #1151 is closed (for deleting the project once the PR is merged and we want to tear down the ephemeral deployment)
 
**Describe the solution you'd like**
We already have the `supabase projects api-keys` command which returns the anon/service_role API keys. It could be a nice enhancement to also include the JWT secret value here.

**Describe alternatives you've considered**
I'm not aware of any alternative solution for dynamically fetching the JWT secret for a new project.

**Additional context**
N/A

**Comment by sweatybridge** [comment]
Hi @cdimitroulas, we considered exposing jwt secret through the api but decided against it to prevent over exposing.

Considering your use case, I think [preview branching](https://github.com/supabase/cli/pull/1313) could be a good fit. These newly added commands allow you to spin up ephemeral branch projects hosted on Supabase for testing and development. You will be able to safely fetch db password and jwt secret for these branches since they are isolated from the production project.

We will soon roll out preview branching for alpha testing. If you would like to be considered for early access, do file a `Feedback` through our dashboard.

**Comment by cdimitroulas** [comment]
Thanks @sweatybridge! I've sent a message through the `Feedback` form in the dashboard to ask for early access to see if this will work for us 👍

**Comment by sweatybridge** [comment]
Thanks for taking the time to sign up! Do note that one of the prerequisites for branching is to enable org level billing. You can make the switch via the org dashboard https://supabase.com/dashboard/org/_/billing.

We will be reaching out again in a couple of weeks to those eligible. Appreciate your patience!
