### ISSUE TITLE
Run supabase db start fails in ci 

### ISSUE THREAD

**Issue by oldbettie** [supabase/cli#1359]
**Describe the bug**
I have an interesting bug. I have validated that even when creating a pr with no changes I get the same error in ci

Applying migration 20230619010515_remote_commit.sql...
ERROR: relation "flow_state_created_at_idx" already exists (SQLSTATE 42P07)                            
At statement 0: CREATE INDEX flow_state_created_at_idx ON auth.flow_state USING btree (created_at DESC)

in CI the action runs `supabase db start` however it fails after apllying remote_commit.sql
I have checked it runs correctly in localhost with the same command

**Expected behavior**
Expect the ci tests to run correctly.

**Desktop (please complete the following information):**
 - OS: mac os
 - Version of CLI [v1.68.6] or latest
 - Version of Node.js [e.g. v18.*]

**Additional context**
This is a weird one I cant find anything online and it doesn't seem to effect the production project.
obviously I could drop the index however I am not sure that is the best approach.

**Comment by sweatybridge** [comment]
Could you check if your setup-cli action is pinned to version 1.68.6? For example,

```yaml
  - uses: supabase/setup-cli@v1
    with:
      version: 1.68.6
```

This should help your CI start successfully. However, the underlying issue is that the `remote_commit.sql` file was generated by an older version of CLI and it contained `auth` schema changes where it shouldn't.

I would recommend fixing it long term by updating your local CLI to latest version, delete local migration files, drop the `supabase_migrations.schema_migrations` on your hosted database, and rerun `supabase db remote commit`. This ensures your remote_commit file is up to date.

**Comment by oldbettie** [comment]
locking the cli worked. Thankyou!

I will look at updating the cli in coming weeks. although that looks a bit daunting deleting all the migrations and then remote committing wont delete all the migrations in the remote?

**Comment by jacquesdev** [comment]
Hi @sweatybridge 

I'm stuck on a similar issue, but I've never used supabase before, so I'm trying to (I guess) use a schema that clashes with what was originally added.

Can I still run all these commands 
delete local migration files, drop the supabase_migrations.schema_migrations on your hosted database, and rerun supabase db remote commit.

and not break all the existing code?

**Comment by sweatybridge** [comment]
Yes, the instructions are still valid. But there's also an easier way now 

```bash
rm -rf supabase/migrations
supabase migration repair --reverted
supabase db pull
```
