### ISSUE TITLE
Reduce CPU usage by reducing/improving health checks

### ISSUE THREAD

**Issue by probablykasper** [supabase/cli#1367]
**Is your feature request related to a problem? Please describe.**
High CPU usage while idle (~25%).

**Describe the solution you'd like**
There is a `--ignore-health-check` option, but I assume health checks are there for a reason. Maybe there could be some way to improve CPU usage while keeping health checks.

Or other ways to reduce CPU usage

**Comment by sweatybridge** [comment]
Our current health check frequency is set to 2s because we wanted the CLI to respond quicker on `supabase start`. It needs to know when services are up before running migrations or other operations.

I think the ideal fix would be to upgrade docker engine once `start-interval` flag is supported https://github.com/moby/moby/issues/45897. It would allow us to use a high frequency when starting containers, and a low frequency after services become healthy to reduce idle cpu usage.

Alternatively, we can tune each service individually to balance the tradeoff between startup time and idle cpu usage. But it's gonna be a lot of work that I'm not sure if it's worthwhile.

**Comment by sweatybridge** [comment]
I just found out that querying the container health api from cli directly can serve as an alternative to `start-interval` flag. I've increased health check interval to 10s and tested on intel mac with `docker stats`. Idle cpu usage should be around ~5% now.

Let me know if it works for you too `npx supabase@beta start`.
