### ISSUE TITLE
Change docker ip in port from 0.0.0.0 for supabase start local development.

### ISSUE THREAD

**Issue by 0xBigBoss** [supabase/cli#1397]
is there anyway to change the binding IP for local supabase from 0.0.0.0 to 127.0.0.1? 

![image](https://github.com/supabase/cli/assets/95193764/8f0ce163-7527-4443-abf9-11fafb66511f)
 
supabase cli is also not respecting the /etc/docker/daemon.json default IP

![image](https://github.com/supabase/cli/assets/95193764/2a8772bd-8d78-4d0a-85ec-0959e1d24c4a)

**Comment by daniel-j-h** [comment]
Coming from https://github.com/supabase/cli/issues/1977

When running supabase start or supabase db start it looks like services are getting exposed on the network, such as the postgres database. I believe this is because when we start containers they bind to all network interfaces instead of just localhost

**This is both unexpected and dangerous to have services exposed publicly on the network.**

Especially because the locally running services are not secured in any way: someone in the same cafe Wifi as I am can run `psql` against my host and is in without any credentials

    $ psql --host 192.168.2.101 --port 54322 --user postgres

    psql (15.5 (Ubuntu 15.5-1.pgdg20.04+1), server 15.1 (Ubuntu 15.1-1.pgdg20.04+1))
    Type "help" for help.

    postgres=>

This works, I just tested it from a second computer to get access to my laptop's supabase stack running from `supabase start`

---

Ideally we'd expose services only on localhost - the equivalent of

    docker run -p 127.0.0.1:54322:54322

Here's an idea how it could work
- By default all sub-commands starting services start them on 127.0.0.1 only
- Sub-commands starting services get a flag like `--host 0.0.0.0` or a binary flag like `--expose-publicly`

**Comment by jmath3912** [comment]
any updates regarding this? i find it odd that supabase says its listening on localhost when its really listening on all interfaces

**Comment by sweatybridge** [comment]
Binding only to localhost interface is now possible in beta release with custom docker network support. For eg.

```bash
docker network create -o 'com.docker.network.bridge.host_binding_ipv4=127.0.0.1' local-network
npx supabase@beta start --network-id local-network
```

**Comment by ChanningJacobs** [comment]
I'm concerned that this documentation may be incorrect for Docker Desktop on MacOS. I followed the Supabase Local Dev & CLI [guide](https://supabase.com/docs/guides/local-development). I'm still seeing ports are bound to 0.0.0.0 on my host after running:

```
docker network create -o 'com.docker.network.bridge.host_binding_ipv4=127.0.0.1' local-network
npx supabase start --network-id local-network
```

I'm checking for bound ports using:

```
docker ps
```

and

```
lsof -i +c 0 | grep docker
```

Both ipv4 and ipv6 ports appear to be exposed.
