### ISSUE TITLE
Postgres: Requested image not found

### ISSUE THREAD

**Issue by chriscasper** [supabase/cli#1582]
**Describe the bug**
When running `supabase start` I am getting the following:
```
Error response from daemon: manifest for public.ecr.aws/supabase/postgres:14.1.0.13 not found: manifest unknown: Requested image not found
```

I have Supabase CLI version 1.100.1 installed.

This is having the same issue on the latest beta branch and 1.100.1

**To Reproduce**
1. Install the CLI
2. Try and spin up Supabase locally.

**Expected behavior**

Supabase should spin up locally and start the docker containers.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 13.6
 - Browser (if applicable) [e.g. chrome, safari]
 - Version of CLI [e.g. v1.60.0]
 - Version of supabase-js (if applicable) [e.g. v2.22.0]
 - Version of Node.js (if applicable) [e.g. v16.20.0]

**Additional context**

**Comment by sweatybridge** [comment]
This could happen if your hosted project is running on pg14 but your `supabase/config.toml` specifies `major_version = 15`. A quick fix is to remove `supabase/.temp/postgres-version` file which is created every time you link a project.

A long term fix is to upgrade your hosted project to pg15 or downgrade your local dev to `major_version = 14` so that they are in sync.
