### ISSUE TITLE
Run new migrations against local DB

### ISSUE THREAD

**Issue by yowzadave** [supabase/cli#166]
There is a CLI command, `supabase db push`, which runs any new migrations against the remote DB. Shouldn't there be a similar command to run any new migrations against my local DB? For example, if multiple developers are working locally, they will need to migrate their local db when another developer pushes an update. Is it recommended that they simply do a `supabase db reset` in this case, erasing any local data they might have?

**Comment by soedirgo** [comment]
Yeah, you'd have to do `supabase db reset` in this case. The assumption for local dev is that data is transient and we're mostly interested in the schema. You can run `supabase db changes` before running `supabase db reset` and run the changes afterwards.

Note that for `supabase db push` there's a consistency check happening - your remote db's migrations must be a subset of your local migrations, otherwise it would fail. So if another developer pushed a migration, you'd need to pull that migration (from version control) to push a new migration.

For local db, it might get tricky if you modified the schema, then run the new migrations. This isn't a big problem for the remote db since the expectation is you'd only do schema changes from migrations.
