### ISSUE TITLE
column "owner_id" of relation "objects" does not exist

### ISSUE THREAD

**Issue by muezz** [supabase/cli#1665]
**Describe the bug**
On `supabase start` I get this error: `column "owner_id" of relation "objects" does not exist`

**To Reproduce**
1. Dump `--data-only` in `seed.sql`
2. Perform `supabase db pull`
3. Run `supabase start`

**Expected behavior**
I know that this column was modified recently. Maybe there is a version mismatch?

**Desktop (please complete the following information):**
 - OS: macOS
 - Version of CLI v1.112

**Comment by sweatybridge** [comment]
Could you create a support ticket? This looks like an issue with storage v3 migration for your remote project @fenos

**Comment by muezz** [comment]
@sweatybridge I have created a ticket although there was no option to directly link the ticket to CLI or Local Dev.

**Comment by GraesonB** [comment]
This exact problem has been a bit of a blocker for my team, would love to know how to resolve this.

**Comment by sweatybridge** [comment]
This usually happens when your remote project is on storage v2 but your local dev is on v3.

You can verify by running `select * from storage.migrations` on your remote project. The last migration id for v2 is 15 and for v3 is 17. 

You can upgrade your storage to v3 yourself to unblock. The migrations are open sourced here https://github.com/supabase/storage/tree/master/migrations/tenant. You want to run both 16 and 17 on your remote project. 

After that, you also need to `dump --data-only` again to recreate seed.sql.

Hope it helps.

**Comment by muezz** [comment]
@sweatybridge I ran this query and I got 17 as my last ID and I still get this error. What should I do?
<img width="867" alt="image" src="https://github.com/supabase/cli/assets/100420605/44f8cd24-a4c8-410a-98d6-eec87d1f53db">

**Comment by GraesonB** [comment]
> This usually happens when your remote project is on storage v2 but your local dev is on v3.
> 
> You can verify by running `select * from storage.migrations` on your remote project. The last migration id for v2 is 15 and for v3 is 17.
> 
> You can upgrade your storage to v3 yourself to unblock. The migrations are open sourced here https://github.com/supabase/storage/tree/master/migrations/tenant. You want to run both 16 and 17 on your remote project.
> 
> After that, you also need to `dump --data-only` again to recreate seed.sql.
> 
> Hope it helps.

@sweatybridge Thanks, this certainly pointed me in the right direction. Turns out my remote is on v3 but local dev is on... v2.5? On my remote db I have up to 17, but on my local setup its 16 not 15. This problem also exists in my GitHub actions for type checking, I've had to disable our actions for now because of this. I've added 17 to the bottom of my most recent migration and it worked like a charm. Is there a right way of fixing this, or do I just need to manually create a migration file that adds 17 to my local/actions instances?

**Comment by sweatybridge** [comment]
> On my remote db I have up to 17, but on my local setup its 16 not 15.

Another possibility is that your local project is on Postgres 14. Could you confirm by checking the major version specified in `supabase/config.toml`?

In either case, I will have to patch the schema for pg14 projects.

**Comment by sweatybridge** [comment]
I've updated default storage version to address this in `npx supabase@beta start`. Feel free to reopen if you are still running into this.

**Comment by GraesonB** [comment]
> Another possibility is that your local project is on Postgres 14. Could you confirm by checking the major version specified in supabase/config.toml?

My major_version in my toml file is 15 actually.

**Comment by muezz** [comment]
@sweatybridge My major version is 15 too

**Comment by muezz** [comment]
I am getting this: `ERROR: column "refreshed_at" of relation "sessions" does not exist` now.

I used `npx supabase@beta` to do `db pull`, `dump` data into `seed.sql, and schema into `schema.sql`.

**Comment by nietsmmar** [comment]
My local setup is missing the 17. storage-migration. How can I update my local supabase to have storage v3?

**Comment by elyobo** [comment]
Just ran into this now as well, `npm i supabase@latest` resolved the issue.
