### ISSUE TITLE
Failed to save database password: Keyring is not supported on WSL

### ISSUE THREAD

**Issue by DavidArmendariz** [supabase/cli#1778]
**Describe the bug**
When trying to link to a supabase project in WSL2 I get the following error: "Failed to save database password: Keyring is not supported on WSL"

**To Reproduce**
1. Run `npx supabase link --project-ref abcdefg` in WSL2
2. Enter the postgres password
3. Get the error "Failed to save database password: Keyring is not supported on WSL"

**Expected behavior**
The database password should be stored locally successfully in WSL2

**Screenshots**
![image](https://github.com/supabase/cli/assets/21047920/be43a362-de1a-412a-b357-4fd526a4ccf2)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS on WSL2
 - Browser (if applicable) [e.g. chrome, safari]: N/A
 - Version of CLI: 1.123.4
 - Version of supabase-js (if applicable) [e.g. v2.22.0]: N/A
 - Version of Node.js (if applicable) [e.g. v16.20.0]: 20.9.0

**Additional context**
* I installed `sudo apt install gnome-keyring` to see if it solved the problem but it didn't.

**Comment by sweatybridge** [comment]
This error is an expected behaviour because we don't officially support saving password on WSL2. There are a few alternatives you can consider

1. Create a `.env` file in your project directory

```
SUPABASE_DB_PASSWORD=<your pass>
```

This will be picked up by the CLI the same way as a password stored in native credentials store.

2. Alternatively, if you insist on using the credentials store on WSL2, you may want to setup gnome-keyring using [these steps](https://github.com/supabase/cli/issues/899#issuecomment-1684263266).
