### ISSUE TITLE
failed to send batch: ERROR: column "is_anonymous" of relation "users" does not exist (SQLSTATE 42703)

### ISSUE THREAD

**Issue by zzt-james** [supabase/cli#2033]
**Describe the bug**
An error occurs while updating locally to a remote DB.

**To Reproduce**
1. npx supabase db pull
2. npx supabase db dump --data-only -f supabase/seed.sql
3. npx supabase db reset

**Expected behavior**
There is no is_anonymous column in the users table of the local auth db.

**Screenshots**
![image](https://github.com/supabase/cli/assets/36973613/24c1ee66-2767-4f39-9989-2e6ebf088905)

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: 
 - Version of OS: MacOS 14.2.1
 - Version of CLI: 1.136.3
 - Version of Docker: ![image](https://github.com/supabase/cli/assets/36973613/df4e32ef-6781-495d-bdf0-33fa7764f9fb)
 - Versions of services: ![image](https://github.com/supabase/cli/assets/36973613/78b8200a-1c2a-4fbb-b9bc-175d2271c2c4)

**Additional context**
 - Version of Node.js v18.17.1

**Comment by sweatybridge** [comment]
Based on output from `supabase services`, it appears that your remote gotrue version is ahead of local. You should be able to fix it by relinking your project, ie.

```bash
npx supabase db pull
npx supabase db dump --data-only -f supabase/seed.sql

npx supabase stop --no-backup
npx supabase link
npx supabase start
```

**Comment by zineanteoh** [comment]
> Based on output from `supabase services`, it appears that your remote gotrue version is ahead of local. You should be able to fix it by relinking your project, ie.
> 
> ```shell
> npx supabase stop --no-backup
> npx supabase link
> npx supabase start
> ```

this works -- thank you 🙌 

follow up question:
- is there a way to manually upgrade the `supabase services` version? 
it turns out that after unlinking from the project, the local version defaults back to previous ones. 

reasons: 
- want to ensure dev's locally hosted supabase is up-to-date without linking to staging/prod db 
- want to minimize chances of messing with staging/prod db

**Comment by sweatybridge** [comment]
> is there a way to manually upgrade the supabase services version?

There's a `supabase/.temp` directory created after linking that contains the service version files. Unlinking will delete them but you can recreate manually to have CLI pick up those updated versions. 

Bear in mind that although it works in principle, we can't guarantee every combination of service version works due to the maintenance complexity involved.

**Comment by zineanteoh** [comment]
> There's a `supabase/.temp` directory created after linking that contains the service version files. Unlinking will delete them but you can recreate manually to have CLI pick up those updated versions.
> 
> Bear in mind that although it works in principle, we can't guarantee every combination of service version works due to the maintenance complexity involved.

awesome! yup, i made sure to use a combination of service versions that are proven to work (i.e. staging/prod) 

also, `supabase unlink` removes the entire `.temp` folder (there is no way to keep the folder after unlinking), so i simply removed the `project-ref` file containing the project id. 
<img width="149" alt="image" src="https://github.com/supabase/cli/assets/58854510/491d410f-8e47-47ce-afd1-738d0f282263">

thanks for your help @sweatybridge
