### ISSUE TITLE
Error when attempting to link project

### ISSUE THREAD

**Issue by LeviticusNelson** [supabase/cli#243]
# Bug report

## Describe the bug

When I type `supabase link --project-ref million-ether-webpage` I get 
`Error: Invalid project ref format. Must be like 'abcdefghijklmnopqrst'.`

This might have to do with the name of my project but I removed the '-' symbols and still did not work.

## System information

- OS: MacOS
- Version of supabase-cli: 0.24.1

**Comment by LeviticusNelson** [comment]
nvm I figured out what the project ref was, might need to clarify that better in the documentation.

**Comment by crawfordleeds** [comment]
@LeviticusNelson how do you find your project ref?

**Comment by BernieSumption** [comment]
Since a search for "Invalid project ref format" brings up this page, the solution is:

Go to your project dashboard > Project Settings > General and copy the "Reference ID" value which should be a 20-character lowercase alphabetic string.

Run the command `supabase link --project-ref {your-reference-id}`
