### ISSUE TITLE
Show auth config diff after supabase link

### ISSUE THREAD

**Issue by mezoistvan** [supabase/cli#2552]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After `supabase init`, if the linked and local config is different, there is a message which lists the differences in the config:

```
$ supabase link
Selected project: .................................
Enter your database password (or leave blank to skip): 
Finished supabase link.
WARNING: Local config differs from linked project. Try updating supabase/config.toml
[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
[api.tls]
enabled = false
```

This message does not include all differences. For example if `[auth.email] enable_confirmations` differs, it's not shown. This is misleading and confusing.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to a remote project on supabase.com, enable email auth and **disable** `enable_confirmations`
2. Create a local project and set up `config.toml` with `[email.auth] enable_confirmations` **enabled**.
3. Link your remote project to your local one and see the difference.

## Expected behavior

All diffs should be visible in the message

## System information

- OS: macOS
- Version of supabase cli: 1.187.3
- Version of Node.js: 20

## Additional context

Is there a way to see when a linked config like this was changed? Is there a way to log these config changes on a linked project?

**Comment by kiarafbickers** [comment]
I'm having this same issue.

**Comment by kiarafbickers** [comment]
This might be similar to issue https://github.com/supabase/cli/issues/1483

**Comment by ThingEngineer** [comment]
This is happening again in v1.226.3

No issues, just the warning message after liking and a diff between the local and remote supabase/config.toml.

**Comment by sweatybridge** [comment]
As requested by the original ticket, we have released enhancement to diff the entire auth config between local and linked project. 

You can update your local config.toml according to the suggested diff to resolve the warnings.

**Comment by ThingEngineer** [comment]
Thank you @sweatybridge, since this does not cause an actual problem with anything I don't feel it warrants it's own issue. However, just as an fyi there may be one side effect to consider. 

As `supabase link` needs to be re-run on other occasions such as when a remote service version is a higher version than your local instance or when you change your db password this warning and diff will be shown then as well. And since, for local development environments, site_url and additional_redirect_urls alone will prevent the local config from ever matching the remote config, so the warning message and diff is guaranteed to show on every re-link.
