### ISSUE TITLE
Enabling extensions doesn't work well with SQL migrations

### ISSUE THREAD

**Issue by lukaspili** [supabase/cli#263]
We cannot enable extensions in SQL files because of the error `permission denied for language c` when pushing to remote 
(migration not executed with super user). Se we need to enable extensions in UI.

However this breaks the local development flow with `db reset` because it also removes extensions that were enabled in UI.

**Comment by lukaspili** [comment]
Maybe duplicate of #191

**Comment by soedirgo** [comment]
Yeah, this is not supported right now (tracking on https://github.com/supabase/cli/issues/61). The core issue is you can only connect to the remote DB using `postgres` which is not a superuser, and since some extensions require being superuser, the migrations can't be run.

The workaround is to manage extensions parity manually - for remote DB enable extensions via the dashboard, for the CLI create extensions manually via SQL in `supabase/extensions.sql` (currently undocumented).

**Comment by lukaspili** [comment]
Thanks! Good to know about `supabase/extensions.sql`.
Should we close the issue or redefine as adding this to the documentation?

**Comment by soedirgo** [comment]
👍 will be closing this then - `supabase/extensions.sql` will be deprecated once this gets resolved so we can leave things as is for now.
