### ISSUE TITLE
Cannot run db tests (Permission denied on /tmp)

### ISSUE THREAD

**Issue by rznsid** [supabase/cli#2659]
**Describe the bug**
Cannot run tests using `supabase db test` or `supabase test db`

**To Reproduce**
Run `supabase db test` via the CLI.  The following error is observed:
```
Connecting to local database...
Can't opendir(/tmp): Permission denied
 at /usr/share/perl5/core_perl/App/Prove/State.pm line 422.
Files=0, Tests=0,  0 wallclock secs ( 0.00 usr +  0.00 sys =  0.00 CPU)
Result: NOTESTS
```

**Expected behavior**
Tests begin.

**System information**
- Supabase 1.192.2
- Fedora 39
- Docker 24.0.5

**Additional context**
Have tried to unset the sticky bit on my local /tmp directory using `chmod -t /tmp`, but this does not solve the problem.  There's no selinux alerts raised when I run this command.

I assume it's some sort of permissions setting for the local directory.

**Comment by avallete** [comment]
Thank you for reporting this issue.

It appears that the problem is related to the permissions of the `./<supabase-project>/supabase/tests` directory being mounted into the Docker container, rather than your local `/tmp` directory.

The `supabase db test` command uses Docker to run tests by mounting the `tests` folder into the container with read-only access. The error you're seeing suggests that the `pg_prove` tool is unable to read the contents of this mounted folder due to permission issues.

To diagnose further, could you run the following Docker command to check the permissions on the `/tmp` directory inside the container?

```bash
docker run -v /<your-project-path>/supabase/tests:/tmp:ro -it supabase/pg_prove:3.36 /bin/sh -c "ls -lRa /tmp"
```

This will help determine if the permissions on the `tests` folder are causing the issue. I wasn't able to reproduce the "Can't opendir" error with various permission settings, so examining the output of this command will provide more insights.

I’ll continue to investigate and update you with any findings.

**Comment by simonwhittenbury** [comment]
Thanks for investigating @avallete.

Running the above command results in:
`/tmp:
ls: can't open '/tmp': Permission denied
total 0`

I believe the issue relates to selinux being enabled within docker on my development machine.  I have the `--selinux-enabled` flag added as an option to my docker sysconfig.

I think the issue is similar to the issue noted here, also concerning supabase: https://blog.ryanmartin.me/selinux-containers.

If I modify the command to use the `Z` relabel bind mount option (`docker run -v <my_project_dir>/supabase/tests:/tmp:Z -it supabase/pg_prove:3.36 /bin/sh -c "ls -lRa /tmp"`), I can see output:
```
/tmp:
total 16
drwxr-xr-x    3 50445    50445         4096 Sep  4 19:02 .
drwxr-xr-x    1 root     root          4096 Sep 13 16:51 ..
...
```

**Comment by avallete** [comment]
Thanks for the link, @simonwhittenbury. It looks like that’s indeed the root of the issue, and your command run confirms it. I think adding the "z" flag to the /tmp directory binding should resolve the issue without affecting other systems. I'll go ahead and create a PR for that.

That said, similar issues could still occur in other parts of the local development environment, since SELinux isn’t part of our current testing pipeline. It might be worth exploring how to include SELinux in our tests to prevent these errors from slipping through.
