### ISSUE TITLE
`supabase gen types` sets `id`s of type `string` as required for `Insert`, rather than optional

### ISSUE THREAD

**Issue by kyleshevlin** [supabase/cli#2773]
**Describe the bug**
I am using Prisma with Supabase locally strictly for migration generation. When I set a model's `id` property to type `String`, when I use the `supabase gen types` command, the `Input` type for `id` is required, rather than optional, like this `id?: string`. 

On `Input` this should be optional, since the `id` will be generated by the database.

**It works fine if `id` is of type `Int` and `autoincremented()`.**

**To Reproduce**
1. Add a model to your `schema.prisma` file

```prisma
model Foo {
  id String @id @db.Uuid
}
```

2. Create the migration and apply it: `npx prisma migrate dev --name=create_foo_table`
3. Generate your types: `supabase gen types --local --lang typescript > ./types/generated.ts`
4. Open your generated types and see that `Foo.Insert.id` is required, not optional

**Expected behavior**
I expect the generated type for `id` for `Insert` to be optional. As stated before, it is optional when `id` is of type `Int`.

**Screenshots**
Please notice the `id` is required on `Insert` for the `users` in this example
![Screenshot 2024-10-16 at 10 46 30 AM](https://github.com/user-attachments/assets/f95ad343-7dc6-4a8b-874e-43efbe2ddeb9)

**System information**
Rerun the failing command with `--create-ticket` flag.
 - Ticket ID: [e.g. ab1ac733e31e4f928a4d7c8402543712]
 - Version of OS: [e.g. Ubuntu 22.04]
 - Version of CLI: [e.g. v1.60.0]
 - Version of Docker: [e.g. v25.0.3]
 - Versions of services: [output from `supabase services` command]

**Additional context**
If applicable, add any other context about the problem here.
 - Version of supabase-js [e.g. v2.22.0]
 - Version of Node.js [e.g. v16.20.0]

**Comment by avallete** [comment]
Hey @kyleshevlin,

Thanks for reporting this! I looked into it and believe I understand the underlying issue.

It stems from how Prisma generates the database code for your migrations. Using your example, a generated migration might look like this:

```sql
CREATE TABLE "Foo" (
    "id" UUID NOT NULL,

    CONSTRAINT "Foo_pkey" PRIMARY KEY ("id")
);
```

When Prisma introspects this, it generates the types. The issue isn't really that the column is treated as a "string," but that it lacks a "default value" at the SQL level. As a result, the database can't insert a new row without explicitly providing an "id" value. For example, running:

```sql
INSERT INTO Foo DEFAULT VALUES;
```

would fail because the "id" column requires a value. Prisma handles this differently than Supabase, relying on runtime-inserted values by the ORM to ensure consistency. Every time you insert with Prisma, it generates a query like:

```sql
INSERT INTO Foo(id) VALUES (${prisma.generate_uuid()});
```

To match the behavior you’re looking for, you can define your table with a default value for the "id" column, like so:

```sql
CREATE TABLE "Foo" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),

    CONSTRAINT "Foo_pkey" PRIMARY KEY ("id")
);
```

This is possible with Prisma but requires [some additional configuration](https://www.prisma.io/docs/orm/prisma-migrate/workflows/native-database-functions#how-to-install-a-postgresql-extension-as-part-of-a-migration).

In your case, the Prisma schema would look like this:

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["postgresqlExtensions"]
}

datasource db {
  provider   = "postgresql"
  url        = env("DATABASE_URL")
  extensions = [pgcrypto]
}

model Foo {
  id String @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
}
```

This should generate the correct SQL:

```sql
CREATE TABLE "Foo" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),

    CONSTRAINT "Foo_pkey" PRIMARY KEY ("id")
);
```

Once you've set this up, generating types should work as expected.

Hope this helps! Let me know if you run into any further issues.

**Comment by kyleshevlin** [comment]
Ahhh, that makes sense @avallete. Thank you for the explanation.
