### ISSUE TITLE
Supabase db push should support migration sub directories

### ISSUE THREAD

**Issue by FrancescoMasaia** [supabase/cli#2881]
**Is your feature request related to a problem? Please describe.**

It could be interesting to have the support for push migration for subdirectories instead of only the main directory of supabase/migrations
that could be helpful in order to have features or scheme separated for each migration, specially in bigger projects i think that something like that is essential.

**Describe the solution you'd like**

I would like the script to iterate over
supabase/migrations/**/*.sql
instead of only
supabase/migrations/*.sql

**Describe alternatives you've considered**

The other alternative is naming convention but that doesn't help to pre filter easily the files in the file explorer

**Additional context**

**Comment by sweatybridge** [comment]
We will probably support this by allowing custom migrations path to be declared in config.toml, similar to https://github.com/supabase/cli/issues/2139#issuecomment-2055650677

**Comment by GitTorres** [comment]
Will a single custom migration path really be the solution here? I too have an interest in organizing my migrations folder by using subdirectories because it's a huge pain to search through to find the right SQL statements to adjust.  

example:

-  subdirectory for each table I've changed.  That way I know the last file in each folder is the latest sql for that view.

```
migrations/vw_some_view
migrations/vw_some_other_view
```

Is the current vision for custom paths in the config.toml really supporting this?

**Comment by FrancescoMasaia** [comment]
I don’t think so, but that was my same necessity, and making this possible would be a very little change on the supabase cli (just using a recursive file list instead of looking in the main directory).Il giorno 20 nov 2024, alle ore 20:52, Jose Torres ***@***.***> ha scritto:﻿
Will a single custom migration path really be the solution here? I too have an interest in organizing my migrations folder by using subdirectories because it's a huge pain to search through to find the right SQL statements to adjust.
example:

subdirectory for each table I've changed.  That way I know the last file in each folder is the latest sql for that view.

migrations/vw_some_view
migrations/vw_some_other_view

Is the current vision for custom paths in the config.toml really supporting this?

**Comment by sweatybridge** [comment]
> I too have an interest in organizing my migrations folder by using subdirectories because it's a huge pain to search through to find the right SQL statements to adjust.

That's a slightly different issue. I believe a nice solution for that is to use declarative schemas. So you would declare all your tables once in `supabase/schemas` directory and use db diff to generate migrations against the declared schema when making changes.

This is currently lacking some docs so I will try to explain the process more in a docs update.

See also https://github.com/supabase/cli/pull/2099

**Comment by GitTorres** [comment]
Thanks for the idea @sweatybridge! Much appreciated. I'll give that approach a try.

**Comment by Ross-Hartigan-Work** [comment]
@sweatybridge  This feature would be incredibly helpful - We are starting to get a HUGE list of sql files now as our project gets bigger and bigger - especially when working on a new feature request that will have a lot of complex migrations - we could chuck all of it into one sql file but that makes it really really difficult to review in Git it would be really nice to supabase/migrations/{feature-name}/**.sql and then have separate files split up into bit sized chunks for reviewing and make it a lot more condensed and easier to follow rather than now having like 50+ sql files all in one folder :D
