### ISSUE TITLE
Feature Request: Make eject actually eject the docker-compose.yml located in .supabase instead of regenerating it

### ISSUE THREAD

**Issue by ff6347** [supabase/cli#29]
# Feature request

From the work with other cli's that use the term `eject` as a command I expect that I get the current configuration written to my working directory and it only should work after I ran an `init` command.

## The Problem

Currently the `eject` behaves more like a `generate` command that has no relation to the setup created with `init`.

This blocks to issue #28, since generating prefixed container names would only make sense if the names persist when ejecting the project.

## The Solution

For me the expected flow would be:

1. setup new project with `init`
2. move the content of `.supabase/**` to the working directory with `eject` without running  `function generate` again

I guess it is okay from the UX that there is no direct way to to generate the files directly in the working directory since I guess the cli will be used to do other things like migration etc in the future.

**Comment by kiwicopple** [comment]
I suspect we might start filling the local docker-compose with a few things that you don't want "in production" (eg [inbucket](https://github.com/inbucket/inbucket) for managing emails locally)

so perhaps we need 2 concepts:

1. an eject which gives you a full [production](https://github.com/supabase/supabase/tree/master/docker) setup 
2. an eject which give you a local development setup outside of `.supabase`

@ff6347 - I'm wondering about the purpose of 2? Can't you just modify the files in the `.supabase` directory? Is it because you want them all in git?

**Comment by ff6347** [comment]
Of course I *can* edit things in the `.supabase/` folder, since it is not in git and created by the cli it suggests (implicitly) that I should not do that. If I edit it I want this under version control. Putting that folder under VC brings up another problem (service_role and anon key in kong.yml). So I rather don't do that.

What I want from `eject` is a setup that I can tweak and deploy myself with all the possible configuration I added via the cli (port, host, … tbd). It does not have to be production ready. It should only reflect the current state. I even find it good having inbucket still in there. Maybe I'm not done with development but I want to add additional containers into that docker network, work with a different db or something else.

Nice to have would be:

* anon and service_role key generation
* modifcation of docker-compose.yaml & kong.yaml to remove the hardcoded keys (could create a .env file which can be consumed by docker compose, don't know about kong)




Concept 2 is IMO not that relevant. If I eject it is up to me what I do with it. It shouldn't be bound to the cli anymore.

**Comment by kiwicopple** [comment]
OK sounds good, thanks for clarifying and giving some more context for your usecase

> Concept 2 is IMO not that relevant

Over time the "local" dev and the "production" docker will be conceptually different. We are going to add more images the "local dev" docker-compose - things like docker images for migrations, or double postgres databases for "diffing". Since we also use this cli for the [self-hosting setup](https://supabase.io/docs/guides/self-hosting#option-1-using-our-cli), we definitely need a way to get a "production ready" setup.

So with this context:

- you want to "eject" docker-compose should include all the modifications you chose during setup
- you want some images that are used for local development (like inbucket), although it's unlikely other developers would want to deploy all the images that we have planned. We should either:
  - copy everything over (probably adding comments to the docker-compose about what is safe to remove during production)
  - ask the user what they want to keep when copying everything over
  - create another whole command for getting a production-ready setup (eg, don't use `eject`)

Bobbie is back working again soon, so I will discuss with him

**Comment by soedirgo** [comment]
We no longer have `supabase eject`, so closing this.
