### ISSUE TITLE
`supabase db reset` Error reloading PostgREST schema cache

### ISSUE THREAD

**Issue by probablykasper** [supabase/cli#294]
# Bug report

## Describe the bug

When running `supabase db reset`, I get this error:
```
Error: Error reloading PostgREST schema cache: Error response from daemon: Cannot kill container: supabase_rest_limey: Container c3ab24899b3c8d822145ec89b854a23c121f3f2d1652b965d09cd70045bf5029 is not running
```

## To Reproduce

Not sure what caused this to start happening

## System information

- OS: macOS
- Version of supabase-js: 0.28.1
- Version of Node.js: 16.15.0

**Comment by probablykasper** [comment]
I've tried doing that, but didn't fix it unfortunately. iirc running `supabase stop` didn't work.

I've had this issue twice, and fixed it by manually removing all Docker containers and images through CLI (Docker Desktop gave an error)

**Comment by Marviel** [comment]
Yeah, seems like the`supabase stop` script could use a touch-up -> Maybe it should be able to detect when there was an issue stopping the containers, and provide the workaround as a suggested output on stdout? @soedirgo

**Comment by sweatybridge** [comment]
To address this specific issue of `db reset` failing, we no longer return an error when PostgREST container is not found. https://github.com/supabase/cli/blob/main/internal/db/reset/reset.go#L216 Reason is purging schema cache is more of a post run action that shouldn't affect the exit code of `db reset`.

Regarding the broader issue of `supabase stop` not working, we would need more details to reproduce, such as screenshots or error logs, because the code for stop command looks ok to me https://github.com/supabase/cli/blob/main/internal/stop/stop.go#L29. Once we know the exact cause, it will be easier to come up with a proper fix. Let's track this in a new ticket if you agree.

**Comment by probablykasper** [comment]
Sounds good! I've only ran into this twice, so I'll just make sure to open another issue if it ever happens again
