### ISSUE TITLE
supabase remove

### ISSUE THREAD

**Issue by sroussey** [supabase/cli#32]
# Feature request

A command to remove everything that supabase init installed (both local files and the docker containers). This would allow for a clean re-install.

**Comment by btelles** [comment]
Agreed. In fact, I've found that if I ever shutdown wsl2 manually with the containers still running, they exit but are not automatically cleaned up. In order to start supabase again I have to manually remove the containers with something like this:

```
docker container ls -a --format="{{.Names}}" --filter name=supabase* | xargs -I {} docker container rm {}
```
Either a 'remove' action or requesting permission to delete existing supabase_* containers would solve this nicely.

**Comment by ozum** [comment]
I got the following error when IDE crashed or shut down manually:
`Error: Error response from daemon: Conflict. The container name "/supabase_db_......" is already in use by container "bf6d...". You have to remove (or rename) that container to be able to reuse that name.`

Thanks to @btelles' solution is a good workaround for me. I added it as an npm script. However, it would be nicer if it is supported by CLI natively.

**Comment by soedirgo** [comment]
This issue was for the old Node.js CLI, but now you can do this with `supabase stop`.

**Comment by innomon** [comment]
the following command worked for me:
`docker images | grep supabase |  awk '{print $1":"$2}' | xargs docker rmi`
