### ISSUE TITLE
`supabase init`: replace invalid chars in generated `project_id` with `_`

### ISSUE THREAD

**Issue by Yonatan-T** [supabase/cli#483]
# Bug report

## Error on '`supabase start`'

trying to follow the instuctions on local devlopment as writtenin the docs 
https://supabase.com/docs/guides/functions#developing-locally

when running `supabase start` its pulls several images then i get a error:
`Error: Error response from daemon: Invalid container name (supabase_db_functions demo), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
`

and when i try running` supabase functions serve hello-world` i get get (obviously..) another error :
`Error: supabase start is not running.`

running in windows 10 with docker installed

**Comment by soedirgo** [comment]
Sorry about that - can set `project_id` in `supabase/config.toml` to e.g. `functions_demo`?

**Comment by Yonatan-T** [comment]
> Sorry about that - can set `project_id` in `supabase/config.toml` to e.g. `functions_demo`?

indeed , i updated the `project_id` in `supabase/config.toml` to the project id ( it was initialy set to the directory name)
now everything is working properly

Thank you.

**Comment by soedirgo** [comment]
Sorry, I'm repurposing this issue to fix the generated `project_id` if you don't mind! Feel free to unsubscribe.

**Comment by hyunbinseo** [comment]
Currently, the [Local Development](https://supabase.com/docs/guides/cli/local-development) documentation guides the user to run `init` and `start` consecutively. However, this causes the following error.

[Local Development]: https://supabase.com/docs/guides/cli/local-development

> Error: Error response from daemon: Invalid container name (supabase_db_@), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

This is because `supabase init` generates a `config.toml` file with `project_id = "@"`.

Adding steps to edit the `config.toml` file would help.
