### ISSUE TITLE
Utility command for running pg_dump from postgres container

### ISSUE THREAD

**Issue by mclean25** [supabase/cli#485]
# Feature request

I frequently have issues with having version mismatches between my local version of postgres and the version of postgres on the database I'm trying to run `pg_dump` from. It would be cool if there was a utility CLI command that could run `pg_dump` from the Supabase service itself. Something like `supabase database dump`, maybe with some options for pointing to different databases (eg: database running at supabase.com).

**Comment by sweatybridge** [comment]
Hi @mclean25, I'm going to link this issue to https://github.com/supabase/cli/issues/389 since we plan to address the mismatched postgres version issue soon.

Regarding pg_dump, we currently have a command `db remote commit` that dumps schema from the linked project. It uses [pg_dump internally](https://github.com/supabase/cli/blob/main/internal/db/remote/commit/templates/dump_initial_migration.sh) the first time it is run. Do you need to run pg_dump more frequently? It would be great if you could clarify this use case more for prioritisation.

**Comment by sweatybridge** [comment]
We have added `supabase db dump` command to address this use case.
