### ISSUE TITLE
Unable to insert row after creating a table in seed.sql

### ISSUE THREAD

**Issue by GZGavinZhao** [supabase/cli#641]
# Bug report

## Describe the bug

Unable to create a table and then insert a row when using `supabase start`.

## To Reproduce

1. Go to `supabase/seed.sql`.
2. Add the following code:
```sql
create table example (
  foo boolean,
  bar int
);

INSERT INTO example (foo, bar) VALUES (3, true);
```
3. Run `supabase start`.
4. See error: `Error: ERROR: relation "example" does not exist (SQLSTATE 42P01)`.

## Expected behavior

Row is inserted correctly and no error appears.

## Debug Output

```
Seeding data supabase/seed.sql...
2022/11/26 21:56:08 PG Send: {"Type":"Parse","Name":"lrupsc_1_0","Query":"create table example (\n  foo boolean not null,\n  bar int not null\n)","ParameterOIDs":null}
2022/11/26 21:56:08 PG Send: {"Type":"Describe","ObjectType":"S","Name":"lrupsc_1_0"}
2022/11/26 21:56:08 PG Send: {"Type":"Sync"}
2022/11/26 21:56:08 PG Recv: {"Type":"ParseComplete"}
2022/11/26 21:56:08 PG Recv: {"Type":"ParameterDescription","ParameterOIDs":[]}
2022/11/26 21:56:08 PG Recv: {"Type":"NoData"}
2022/11/26 21:56:08 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
2022/11/26 21:56:08 PG Send: {"Type":"Parse","Name":"lrupsc_1_1","Query":"INSERT INTO example (foo, bar) VALUES (3, true)","ParameterOIDs":null}
2022/11/26 21:56:08 PG Send: {"Type":"Describe","ObjectType":"S","Name":"lrupsc_1_1"}
2022/11/26 21:56:08 PG Send: {"Type":"Sync"}
2022/11/26 21:56:08 PG Recv: {"Type":"ErrorResponse","Severity":"ERROR","SeverityUnlocalized":"ERROR","Code":"42P01","Message":"relation \"example\" does not exist","Detail":"","Hint":"","Position":13,"InternalPosition":0,"InternalQuery":"","Where":"","SchemaName":"","TableName":"","ColumnName":"","DataTypeName":"","ConstraintName":"","File":"parse_relation.c","Line":1381,"Routine":"parserOpenTable","UnknownFields":null}
2022/11/26 21:56:08 PG Recv: {"Type":"ReadyForQuery","TxStatus":"I"}
2022/11/26 21:56:08 PG Send: {"Type":"Terminate"}
Error: ERROR: relation "example" does not exist (SQLSTATE 42P01)
```

## System information

- OS: Linux amd64
- Version of cli: 1.12.2

## Additional context

When I run the insert statement after I connect to the database using `psql`, it completes successfully, which is really confusing to me... I also tried `INSERT INTO public.example` but it still tells me that `ERROR: relation "public.example" does not exist (SQLSTATE 42P01)`.

**Comment by sweatybridge** [comment]
Hi @GZGavinZhao, the intended way of using `seed.sql` is to write data insertion / deletion only. Schema migrations such as create / alter table should be created under `supabase/migrations/<timestamp>_name.sql`. 

We are looking into ways of better initialising project so that the guide rails are clearer. For now, this is working as intended.

**Comment by sweatybridge** [comment]
Related https://github.com/supabase/cli/issues/599#issuecomment-1312530629

**Comment by idudinov** [comment]
@sweatybridge sorry for bringing this closed issue up, but it looked to me as the most relevant.

In `seed.sql`, I'm not able to insert values to a table that is already created.

So using the latest CLI version (`1.82.6`), I did the following:

0. `supabase start` (with clean volumes)
1. `supabase db dump  -f supabase/seed.sql`
2. `yarn supabase db dump  -f supabase/seed.data.sql --data-only` – it has the necessary `CREATE TABLE "public"."products"` table creation command, and I'm going to populate this table with few rows below.
3. from `seed.data.sql`, copied an `INSERT` (only one for now) statement that I want populate my local db, and inserted it at the end of freshly generated `seed.sql` 
4. run `supabase db reset`
5. getting the `relation "public.products" does not exist (SQLSTATE 42P01)` error

Having the updated `seed.sql` and removing local volumes, I'm not able to do `supabase start` again because of the same error.

I'd love to hear any ideas on how can I have a local db instance with a schema 100% equivalent to the remote db's one, but populated with only some test rows – so this would serve as clean local development setup.

Thanks!

**Comment by sweatybridge** [comment]
The problem is with supabase db dump at step 1. You want to save the dumped schema as a migration file instead of seed.sql. For example 

```
supabase db dump | supabase migration new remote_schema
```

Subsequently you should be able to use seed.sql for the data-only dump.

> I'd love to hear any ideas on how can I have a local db instance with a schema 100% equivalent to the remote db's one, but populated with only some test rows – so this would serve as clean local development setup.

We will have a video guide coming up for this in the following weeks. So stay tuned!
