### ISSUE TITLE
Add back inbucket (supabase-mail) and disable autoconfirm

### ISSUE THREAD

**Issue by soedirgo** [supabase/cli#71]

**Comment by mr-bjerre** [comment]
Any pointers in case I'm able to contribute?

**Comment by soedirgo** [comment]
Hey, sorry this one's lacking context - I saw you went ahead and made a PR 😅

For this one the end goal is to do custom SMTP through the OSS dashboard once it's integrated, and make inbucket opt-in since you may still need to use an email testing server.

So the current approach (autoconfirm, to answer your 2nd question) and inbucket are stopgaps so you can still test emails to some extent. But having inbucket now is fine I think, as long as it's opt-in. I'll add some comments to your PR tomorrow (past midnight atm)

**Comment by mr-bjerre** [comment]
Ah I see. I didn't make it opt in - not sure I'm able too currently since this is my first time even reading golang 😅

On the second question. I don't understand how autoconfirm can help me login though? My understand is that it simply flags confirmation in the auth.users table but I'm probably wrong.

**Comment by soedirgo** [comment]
It's basically the same as this:
<img width="1565" alt="Screen Shot 2021-11-26 at 1 39 14 AM" src="https://user-images.githubusercontent.com/31685197/143483895-bd059aa0-48c9-441c-873d-a6da5538bb63.png">

**Comment by mr-bjerre** [comment]
Sorry but I don't understand. What is the same as those four switches. As I understand the email confirmation; you need to confirm your email in order to login. So with autoconfirm you enable users to login without confirming basically. 

My issue is that I want to login with magic links so there is no way to login without actually receiving those magic links.

**Comment by soedirgo** [comment]
Ah, I see. I'm not familiar with the auth server, so I'm not sure if you can generate a magic link without sending an email. But for normal password login it works as you mentioned.

**Comment by mr-bjerre** [comment]
You can; https://supabase.com/docs/reference/javascript/auth-api-generatelink

However I don't want an unauthenticated user being able to do that. Then I should create some backend endpoint that only exists in development mode and allow anyone to generate those links at that endpoint. 

With inbucket I'd be able to receive those emails instead which is much much nicer 😅

**Comment by mr-bjerre** [comment]
Actually now that I think about it. A workaround could be that if I'm working locally then I console log the generate link instead of sending an invite mail. 

Still the inbucket solution is better imo though.

**Comment by mr-bjerre** [comment]
I just did some testing. 

With the current setup with auto confirmation no links are generated. Not even using `serverSupabase.auth.api.generateLink`. It does work in my PR though
