### ISSUE TITLE
Connection to self hosted database not possible

### ISSUE THREAD

**Issue by jojomatik** [supabase/cli#753]
# Bug report

## Describe the bug

According to https://github.com/supabase/cli/issues/147 it was possible to connect to a self-hosted remote using the connection string. I can't find anything like that documented right now and the `db remote set` command has been deprecated and since removed.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run `supabase db remote set`
2. See syntax explanation

## Expected behavior

It is possible to connect to a self-hosted instance to create, manage and deploy migrations.

## Screenshots

Not applicable.

## System information

Not applicable.

## Additional context

I thought that `supabase link` would be the new command to replace `db remote set` but that seems to only support project-refs on hosted supabase.

This issue is somewhere in between bug, feature request and documentation issue. Feel free to move it to the category you find most fitting. As it seemed to have worked in the past and as I didn't find an meaningful documenation/ migration guide, I personally considered it a bug.

**Comment by hensou** [comment]
I'm also facing the same issue. I could not find anywhere how to make the supabase-cli point to my self-hosted supabase.

**Comment by profiluefter** [comment]
I switched to doing migrations with Flyway for our project however I had do make a somewhat complicated shell script to change the filenames before running so that they work with both the supabase cli and flyway.

I asked about this on the Discord server in october last year but got no answer so I guessed this is a sort of vendor lock in method of making it more convenient to use their cloud offering but I still hope it gets added back.

**Comment by hensou** [comment]
@profiluefter I've poked a bit with the cli code and got it to work. I've used the `supabase_admin` credentials and changed the connection strings from [these functions](https://github.com/supabase/cli/blob/main/internal/db/reset/reset.go#L37-L44) (as I was only interested on the `db reset` command).

With that I'm confident that it is possible to add these features, or at least to have a fork that works with self-hosted scenarios.

**Comment by sduduzog** [comment]
I use dbmate to run my scripts. I use a bash script to prepend the comment `--migrate:up` for each migration created by the cli

**Comment by jojomatik** [comment]
> I use dbmate to run my scripts. I use a bash script to prepend the comment `--migrate:up` for each migration created by the cli

[dbmate](https://github.com/amacneil/dbmate) looks really promising, I will try it out for sure. It would be cool though if it would contain a tool to automatically create schema migrations. I tried out [migra](https://github.com/djrobstep/migra) for that purpose but gave up after not being able to fix some errors.

For my project I decided to dump schema `public` once for the "initial migration" and create schema migrations using pgAdmins Diff Tool. I execute these using the [node-postgres](https://www.npmjs.com/package/pg) package in an express backend.

The migrations from the Diff Tool are not perfect as it does not have enough information to correctly order the statements, but it is a good start and an easy task to reorder them manually (at least for small incremental migrations). The statements to migrate the data have to be written manually though (but I don't think any tool supports this automatically).

**Comment by SteveChurch** [comment]
Is there any update on whether this will be resolved/pipelined? It seems like a regression for self-hosted.

**Comment by linus1703** [comment]
@profiluefter I also think it's a vendor lock-in tactic. They've also removed the "eject" command to create a production docker-compose file.

**Comment by Rid** [comment]
@soedirgo would you be willing to accept PRs to enable this feature? We don't want to spend person hours on the work if it won't be accepted.

**Comment by jsbrain** [comment]
Fun fact: Enabling most of the desired features is like less than 20 LOC. I have a local modified version of the cli that can do the link and migrate stuff and it's just minor changes.

Objectively speaking, considering some historical complaints and after checking the commit history of the cli I generally tend to agree with @linus1703 without wanting to point fingers. Focussing on rolling out paid features is one thing, "randomly" removing specific features that make a management tool usable for self-hosting is another IMO.

**Comment by Rid** [comment]
@jsbrain Do you mind putting your fork up? I'm happy to team up with anyone to maintain a fork if there's not many changes, to hedge against @linus1703 being correct.

**Comment by sweatybridge** [comment]
Before this issue getting out of hand, I just want to clarify that we are always happy to review pull requests from the community as this is an open source project. We are also thankful of the community feedback that continuously helped us refine the product we are building.

There are a few differences between platform and self-hosted that made supporting `db remote set` non-trivial. Primarily because self-hosted injects PostgREST config as environment variables in the container while the platform keeps them in a middleware database. When linking a project, the CLI tries to pull these configs from the remote project so that not only postgres, but other service configs are also kept in sync.

If we can limit the scope of this contribution to just db migrations, it would be much easier to support. I'm happy to add a flag `--db-url` to any `db` subcommands, similar to what we do with [typegen](https://github.com/supabase/cli/blob/d35458e60a1d7238f4aeda6c8af4576841262a09/cmd/gen.go#L55).

**Comment by jsbrain** [comment]
@Rid I actually realized I don't have that copy anymore as it was just a proof of concept, wether it would be possible to potentially create a fork with reasonable complexity. But I wrote down notes for a potential proposal of said fork. Ideally I wanted to wait how this issue turns out before I would spend any more time on this.

Anyhow, I can offer my notes to what would need to change for the features (or at least most of them) to work with self-hosted:

---

## Notes

The values for the db_host are hardcoded, so we need a way to override them.

First, we add the `db_host` to the config file. In [internal/config/config.go](https://github.com/supabase/cli/blob/main/internal/utils/config.go) we add the `RemoteHost` and `RemotePort` fields to the `Db` struct.

```diff
db struct {
  Port         uint `toml:"port"`
  ShadowPort   uint `toml:"shadow_port"`
  MajorVersion uint `toml:"major_version"`

+ RemoteHost string `toml:"remote_host"`
+ RemotePort uint   `toml:"remote_port"`
}
```

Next, in [internal/utils/api.go](https://github.com/supabase/cli/blob/main/internal/utils/api.go) we change the `GetSupabaseDbHost` function to use the `Config.Db.RemoteHost` value if it is set.

```diff
func GetSupabaseDbHost(projectRef string) string {

+ LoadConfig()
+ if Config.Db.RemoteHost != "" {
+   return Config.Db.RemoteHost
+ }

  // TODO: query projects api for db_host
  switch GetSupabaseAPIHost() {
  case "https://api.supabase.com", "https://api.supabase.io":
    return fmt.Sprintf("db.%s.supabase.co", projectRef)
  case "https://api.supabase.green":
    return fmt.Sprintf("db.%s.supabase.red", projectRef)
  default:
    return fmt.Sprintf("db.%s.supabase.red", projectRef)
  }
}
```

Finally, in [internal/utils/connect.go](https://github.com/supabase/cli/blob/main/internal/utils/connect.go) we instruct the cli to use the `Config.Db.RemotePort` value if it is set.

```diff
// Connnect to remote Postgres with optimised settings. The caller is responsible for closing the connection returned.
func ConnectRemotePostgres(ctx context.Context, username, password, database, host string, options ...func(*pgx.ConnConfig)) (*pgx.Conn, error) {
  // Use port 6543 for connection pooling
+ // if the user has not specified a remote_port
+ remotePort := 6543
+ if Config.Db.RemotePort != 0 {
+   remotePort = int(Config.Db.RemotePort)
+ }

  pgUrl := fmt.Sprintf(
-   "postgresql://%s@%s:6543/%s?connect_timeout=10",
+   "postgresql://%s@%s:%d/%s?connect_timeout=10",
    url.UserPassword(username, password),
    host,
+   remotePort,
    url.PathEscape(database),
  )
  // Simple protocol is preferred over pgx default Parse -> Bind flow because
  //   1. Using a single command for each query reduces RTT over an Internet connection.
  //   2. Performance gains from using the alternate binary protocol is negligible because
  //      we are only selecting from migrations table. Large reads are handled by PostgREST.
  //   3. Any prepared statements are cleared server side upon closing the TCP connection.
  //      Since CLI workloads are one-off scripts, we don't use connection pooling and hence
  //      don't benefit from per connection server side cache.
  opts := append(options, func(cc *pgx.ConnConfig) {
    cc.PreferSimpleProtocol = true
  })
  conn, err := ConnectByUrl(ctx, pgUrl, opts...)
  if !pgconn.Timeout(err) {
    return conn, err
  }
  // Fallback to postgres when pgbouncer is unavailable
  config := conn.Config()
  config.Port = 5432
  fmt.Fprintln(os.Stderr, "Retrying...", config.Host, config.Port)
  return pgx.ConnectConfig(ctx, config)
}
```

Now, when we run use the local cli to generate the config, we can use the values we just implemented to point the cli to our own database.

In the local `supabase/config.toml`:

```diff
[db]
+ # Overwrite remote port (disable connection pooling)
+ remote_port = 5432
+ # Overwrite remote host
+ remote_host = "10.10.4.123"
```

Now we should be able to run most of the _db_ and _migration_ related commands, like:

```bash
export DB_PASSWORD="my-password"
go run . db dump -p $DB_PASSWORD -f ./test.dump
```

---

> It might be worth mentioning that I never used **Go** before so I have no idea if this is alright what I did but it works as a proof of concept and as a potential starting point.
