### ISSUE TITLE
Supabase Migrations don't include created buckets

### ISSUE THREAD

**Issue by MisterJimson** [supabase/cli#859]
# Bug report

## Describe the bug

When you diff the DB using `supabase db diff -f <migration_name>` no statements are present that would create a storage bucket.

However you do see RLS policies that reference the buckets that you expect to be present.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Spin up a fresh supabase project with `supabase init` and`supabase start`
2. Create a bucket in the local supabase dashboard
3. Create some RLS policies for access to the bucket
4. Create a db migration using `supabase db diff -f add_bucket`
5. Inspect migration file. Notice that RLS polices are present and mention the bucket name, however there is nothing that creates the bucket,
6. Run `supabase start` to reset the local supabase instance to match your migrations
7. Open supabase studio locally and inspect the buckets section
8. Notice no buckets are present
 
## Expected behavior

Created buckets should persist in migration files so they are present when `supabase start` is ran and can be sync'ed to a hosted remote supabase instance

## System information

- OS: macOS
- Version of supabase-cli: 1.35.0, 1.37.1

**Comment by MisterJimson** [comment]
@bombillazo agreed, but it's the `supabase db diff` command that should create those statements. Just like it does for everything else in the DB.

**Comment by bombillazo** [comment]
Migrations and the cli `diff` command uses `pg_admin diff`, which does not generate nor handle DB data / SQL INSERT statements, they specifically concern with comparing schema differences. These include tables, functions, data types, triggers, etc but not data differences. Buckets added to the table are data differences.

You can, however, customize the generated migration file and add the buckets INSERT statements, which would be the easiest fix.

The other more complex solution perhaps would be an additional cli command or cli flag that generates a custom SQL INSERT migrations specifically for buckets, which would need to be all handled by the cli itself instead of leveraging pg_admin.
