### ISSUE TITLE
Failed to create bin during pnpm install via CI (vercel)

### ISSUE THREAD

**Issue by wottpal** [supabase/cli#860]
When `pnpm install` is running on Vercel it throws the following warning:

```
WARN  Failed to create bin at /vercel/path0/node_modules/.bin/supabase. The source file at /vercel/path0/node_modules/supabase/bin/supabase does not exist.
```

I think this is not during postinstall but while fetching the package.

It runs through, though.

**Comment by sweatybridge** [comment]
Thanks for reporting. I believe this is due to adding the placeholder bin path in package.json. It causes npm to copy the binary before it's downloaded. Unfortunately this was the only way to fix https://github.com/supabase/cli/issues/717 so we have to live with the error until a better solution comes around. 

As an alternative, yarn install is also known to work without such issues.
